### ISSUE TITLE
No module diffusers

### ISSUE THREAD

**Issue by nhandangxl** [XuandongZhao/WatermarkAttacker#2]
Thank you for the awesome project. I have tried following the demo notebook and got the error in importing the module diffusers. I have tried downgrade the version to 0.18.2 but cannot import the ReSDPipeline.
I then check the code and see the ReSDPipeline seems to be the custom pipeline. Can you guide me further on how to solve this?
Thank you

**Comment by XuandongZhao** [comment]
You need to install the modified diffusers in our repo. 
Did you try `pip install -r requirements.txt` and `pip install -e .`?

**Comment by nhandangxl** [comment]
Yes i did, the import only failed at diffusers

**Comment by XuandongZhao** [comment]
Can you uninstall the diffusers and install it again?

**Comment by nhandangxl** [comment]
I downgrade it to version 0.18.2 then i can import the diffusers, but i cannot imort the custom ReSDPipeline. Install the pip requirements get me the version: 0.20.0.dev0.
I run on google colab

**Comment by nhandangxl** [comment]
Seems like i manage to know why the error. It simply because of the system path. When i change from `diffusers` to `src.diffusers`, it now able to start import the module successfully. I still need to track down the path more.
Thank you for the support

**Comment by nhandangxl** [comment]
After changing all `diffusers ` to `src.diffusers` for all module, i am now able to successfully import all. I will now test if i can reproduce the results from the demo notebook.

**Comment by nhandangxl** [comment]
I did manage to successfully run the demo notebook after changing the path as mentioned above.
For RIVAGAN, i got the following error `ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are 
required to explicitly set the providers parameter when instantiating InferenceSession. For example, 
onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)`. Do you know how to fix this?
If i want to show the image after adding watermark and after removing the watermark, which line of codes i need to run or modify, can you guide me?
Thank you

**Comment by nhandangxl** [comment]
I successfully run this awesome project except for the RivaGan, thank you for the great support. I will close this issue
