### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by Kornifikator** [XuandongZhao/WatermarkAttacker#3]
Hello, I tried to install and run the demo.ipynb in a colab notebook, but during the installation process this error occurred:

![grafik](https://github.com/XuandongZhao/WatermarkAttacker/assets/140385139/ea185e48-a7cd-41d4-bd73-f4a134319bcc)

I rerun the installation process several times, but it always ends up with the same result. As you can see 'diffusers' is installed successfully. There is also diffusers folders in the directories.
How can I fix this problem?

**Comment by zrsandwj1314** [comment]
Hello! May I ask if you have resolved it? I also encountered the same problem, I found that the src/diffusers/pipelines/stable_diffusion/pipeline_re_sd.py is located here, but this file also introduces files from the diffusers folder.

**Comment by zkx06111** [comment]
Could #2 help?

**Comment by XuandongZhao** [comment]
I simplified the code. You can install the latest diffuser to run it.
