### ISSUE TITLE
Question about robust experiments for tree-ring watermark

### ISSUE THREAD

**Issue by xinxinzi8** [XuandongZhao/WatermarkAttacker#4]
Hello, author. Could you please offer more information about robust experiments for tree-ring watermark? In tree-ring watermark, it goes through the process of DDIM inversion to extract the watermarks so it involves StableDiffusionPipeline in diffusers package. But your code modifies diffusers, so I want to know if I use the modified diffusers, will the ddim inversion process be affected. And I noticed in the paper the detect acc is used for robust experiments for tree-ring watermark which isn't binary string. So I have doubts on how to calculate the detect acc. I hope to hear back from you, thanks!

**Comment by XuandongZhao** [comment]
For the tree-ring experiment, we conducted it in another environment with their original code and then stored the images. The detection accuracy is evaluated based on the whole image detection as defined in the tree-ring paper.

**Comment by xinxinzi8** [comment]
I got it, thank you for your reply!
