### ISSUE TITLE
how to let RIVAGAN run on gpu

### ISSUE THREAD

**Issue by liwd190019** [XuandongZhao/WatermarkAttacker#5]
as title. The watermarking process of rivagan was quite slow when it was running on my computer. I didn't see it's performed on gpu, which might result in this issue. Can anyone share some ideas to let it run on gpu?

Thanks in advance!

**Comment by XuandongZhao** [comment]
Probably this can help you: https://github.com/ShieldMnt/invisible-watermark/issues/34
